# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
    - sudo apt-get install libgsl0-dev
    - Rscript -e 'install.packages("BH", dependencies = TRUE)'
    - Rscript -e 'install.packages("MASS", dependencies = TRUE)'
    - Rscript -e 'install.packages("RcppEigen", dependencies = TRUE)'
    - Rscript -e 'install.packages("RcppGSL", dependencies = TRUE)'
    - Rscript -e 'install.packages("appell", dependencies = TRUE)'
