# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

install:
    - sudo apt-get install r-cran-rcppgsl r-cran-rcppeigen
    - Rscript -e 'install.packages("BH", dependencies = TRUE)'