---
title: "Log of the Bayes Factors"
author: "Mark Greenaway, Dr John Ormerod"
date: "15/09/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Produce plots of log of Bayes factors, to check that the functions are behaving
correctly.
```{r plot_log_BF}
library(tidyverse)
library(blma)
library(appell)
library(furrr)
plan(multiprocess)

n <- 1000
p <- 100
R2 <- seq(0.01, 0.99, length.out = 10000)
p_gamma <- 50

log_BF_fns <- list(liang_g_n_appell=quo(liang_g_n_appell),
                   liang_g1=quo(liang_g1),
                   liang_g2=quo(liang_g2),
                   log_BF_g_on_n_quad=quo(log_BF_g_on_n_quad),
                   log_BF_Zellner_Siow_quad=quo(log_BF_Zellner_Siow_quad),
                   maruyama=quo(maruyama),
                   robust_bayarri1=quo(robust_bayarri1),
                   robust_bayarri2=quo(robust_bayarri2),
                   ZE=quo(ZE),
                   BIC=quo(BIC))
future_map(log_BF_fns, function(priorfn) {
  name <- rlang::quo_expr(priorfn)
  fn <- rlang::eval_tidy(priorfn)
  future_map_dbl(R2, ~fn(n, p, ., p_gamma)) %>%
    {tibble(R2=R2, log_BF=.)} %>%
    ggplot(aes(x=R2, y=log_BF)) + geom_line() + labs(title=name)
})
```
